emr_config: null
features:
  override: false
features_defined:
  add_new_block_v2: true
  command_center: true
  compute_management: false
  custom_design: true
  data_integration_in_batch_pipeline: true
  dbt_v2: true
  display_local_timezone: true
  global_hooks: true
  interactions: true
  notebook_block_output_split_view: true
  operation_history: true
  polars: true
features_override: {}
help_improve_mage: true
latest_version: 0.9.72
name: unit_3_observability
openai_api_key: null
pipelines: null
platform_settings:
  projects:
    chat_moderation:
      path: chat_moderation
    unit_0_setup: {}
    unit_1_data_preparation: {}
    unit_2_training: {}
    unit_3_observability: {}
project_uuid: 3f635723539840c786c11e59d9574b98
projects:
  chat_moderation:
    path: chat_moderation
  unit_0_setup: {}
  unit_1_data_preparation: {}
  unit_2_training: {}
  unit_3_observability: {}
remote_variables_dir: null
repo_path: /home/src/mlops/unit_3_observability
root_project: false
settings:
  active: false
  uuid: unit_3_observability
spark_config: null
version: 0.9.72
workspace_config_defaults: {}
